name: smiles-extraction
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy<2
  - rdkit=2022.09.5
  - pytorch>=2.2,<3
  - pillow>=10
  - pip
  - pip:
      - transformers>=4.57.0,<5
      - DECIMER>=2.7,<3
      - opencv-python<4.13
